# Generated by Django 5.2 on 2025-06-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_position_description_alter_position_monthly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description_en',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_uk',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='position',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
