# Generated by Django 5.2 on 2025-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_company_course_learning_plan_student_phone_number'),
    ]


    operations = [
        migrations.AddField(
            model_name='position',
            name='monthly_rate',
            field=models.IntegerField(default=0),
        ),
    ]
