# Generated by Django 5.2 on 2025-05-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_experiment_article_experiment2'),
    ]



    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='first_app.department'),
        ),
    ]

