# Generated by Django 5.2 on 2025-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_article_alter_experiment2_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='monthly_rate',
            field=models.IntegerField(default=0),
        ),
    ]
